### ISSUE TITLE
HashTable implementation

### ISSUE THREAD

**Issue by manparvesh** [stlmp/stlmp#113]

**Comment by Bo887** [comment]
@manparvesh Hi, can I work on this issue?

**Comment by manparvesh** [comment]
@Bo887 sure

**Comment by Bo887** [comment]
@manparvesh Thanks. Is there a difference between this issue and the HashMap implementation issue (#115)?

**Comment by manparvesh** [comment]
@Bo887 Oh, I just realized that it's a duplicate, thanks for mentioning that. I will close this issue, let's implement HashMap.
