### ISSUE TITLE
Add linked list implementations

### ISSUE THREAD

**Issue by manparvesh** [stlmp/stlmp#12]
Add implementations for the following, with tests
 - [ ] Circular Linked list
 - [ ] Memory efficient doubly Linked list
 - [ ] Skip Linked list
 - [ ] Unrolled Linked list

**Comment by goyaljai** [comment]
i would like to contribute. thanks

**Comment by manparvesh** [comment]
@goyaljai sure

**Comment by ajeetdsouza** [comment]
I would also like to contribute. Thanks!

**Comment by manparvesh** [comment]
Contents divided into individual issues, so closing this
