### ISSUE TITLE
Add sorting implementations

### ISSUE THREAD

**Issue by manparvesh** [stlmp/stlmp#13]
Add implementations for the following, with tests
 - [x] Heap sort
 - [x] Shell sort

**Comment by rishabh-bansal** [comment]
Will be working on it.

**Comment by goyaljai** [comment]
i would like to contribute. thanks

**Comment by matheuscr30** [comment]
@rishabh-bansal Can I do the Shell Sort?

**Comment by manparvesh** [comment]
@goyaljai @matheuscr30 @rishabh-bansal sure you can contribute, but please first let me update the contributing guide. All the current PRs are not conforming to the existing project structure.

**Comment by j3r3mias** [comment]
Hi @manparvesh, 

I sent #21 with a shell sort implementation and tests. I also edited README and plan to include the algorithm.
