### ISSUE TITLE
Add searching algorithms

### ISSUE THREAD

**Issue by manparvesh** [stlmp/stlmp#14]
Add implementations for the following, with tests:
 - [x] Binary search
 - [ ] Jump search
 - [x] Fibonacci search
 - [ ] Kosaraju's Algorithm (find all SCCs)

**Comment by WilliamStarr** [comment]
`import java.util.*;
import java.io.*;

public class Project3
{
static final int INITIAL_CAPACITY = 5;

public static void main( String args[] ) throws Exception
{
if (args.length < 1 )
{
System.out.println("ERROR: Must enter an int on cmd line (i.e. # of random ints to put in array)\n");
System.exit(0);
}

int numInts2generate = Integer.parseInt( args[0] );


Random randGen =  new Random( 17 ); 
int[] arr = new int[INITIAL_CAPACITY];
int count= 0;
for ( int i = 0 ; i<numInts2generate ; ++i)
{
if ( count==arr.length ) arr = upSizeArr(arr);
insertInOrder( arr, count++, 1 + randGen.nextInt(1000) );
}

arr=trimArr(arr,count); 
printArray( arr );  

} 

static void printArray( int[] arr  )
    {
        for( int i=0 ; i<arr.length ;++i )
            System.out.print(arr[i] + " " );
        System.out.println();
    }

static int[] upSizeArr( int[] fullArr )
{
int[] upSizedArr = new int[ fullArr.length * 2 ];
for ( int i=0; i<fullArr.length ; ++i )
upSizedArr[i] = fullArr[i];
return upSizedArr;
}

static int[] trimArr( int[] oldArr, int count )
{
int[] trimmedArr = new int[ count ];
for ( int i=0; i<count ; ++i )
trimmedArr[i] = oldArr[i];
return trimmedArr;
}

static void insertInOrder( int[] arr, int count, int newVal   )

{

int index = bSearch(arr, count, newVal);
if (index < 0 ) {
index = -(index+1);
}
for( int i =count; i > index; i-- ){
        arr[i] = arr[i-1];
}

arr[index] = newVal; 
}


static int bSearch(int[] a, int count, int key)
{

int lo=0, hi=count-1, mid = 0;
while (hi >= lo) {
mid = lo + ((hi - lo) / 2);

            if (a[mid] == key) return mid;

        if (a[mid] > key) hi = mid - 1;
       
        if (a[mid] < key) lo = mid + 1;

     
   }
   lo = -(lo+1);
return lo; 



}
} `

Really new to this so don't know how to submit things, but here is Binary Search. To test, input an int.

**Comment by abhiii5459** [comment]
@WilliamStarr , Clone the repo "stlmp" and submit a Pull Request

**Comment by manparvesh** [comment]
Hi @WilliamStarr 
I suggest you look at the directory structure first. This project is written in C++. The build instructions are written in the README file. You can take a look at it. And for the tests, you should add another file in the tests folder.

**Comment by WilliamStarr** [comment]
Having trouble installing C++ per those directions. sudo: add-apt-repository: command not found

**Comment by tejas2005** [comment]
Do we have to create our own graph class for implementing kosaraju algorithm

**Comment by manparvesh** [comment]
@tejas2005 you can use the [existing graph implementations](https://github.com/stlmp/stlmp/blob/master/src/graph/adjacency_list.hpp).

**Comment by lucca30** [comment]
For these algorithms you want a general implementation that works with all kind of structs, or you only need something that works with integers?

**Comment by manparvesh** [comment]
@lucca30 I'd prefer an implementation that works with all kinds of structs using templates.

**Comment by goyaljai** [comment]
i would like to contribute. thanks

**Comment by matheuscr30** [comment]
@manparvesh  Can i do the kosaraju?

**Comment by manparvesh** [comment]
@goyaljai @matheuscr30 sure

**Comment by amanharitsh123** [comment]
@manparvesh    Can i do the binary search?

**Comment by amanharitsh123** [comment]
Just hve added a PR for fibonacci search

**Comment by manparvesh** [comment]
@amanharitsh123 there is already a PR for binary search. :+1: for fibonacci search

**Comment by amanharitsh123** [comment]
Have a look ..of FIbonacci search

**Comment by amanharitsh123** [comment]
merge that if u found it correct

**Comment by NishantTanwar** [comment]
Can I go for Jump Search?
