### ISSUE TITLE
Implement Kruskal’s Minimum Spanning Tree Algorithm

### ISSUE THREAD

**Issue by manparvesh** [stlmp/stlmp#40]

**Comment by Brand-Temp** [comment]
Hey, if no one else is working on this I'd love to give it a try!

**Comment by manparvesh** [comment]
@Brand-Temp sure!

**Comment by Brand-Temp** [comment]
Hi @manparvesh I'm trying to build and test however the build script is returning:
```
Scanning dependencies of target googletest
make[2]: *** No rule to make target '../external/googletest/googletest/src/gtest-all.cc', needed by 'CMakeFiles/googletest.dir/external/googletest/googletest/src/gtest-all.cc.o'.  Stop.
CMakeFiles/Makefile2:686: recipe for target 'CMakeFiles/googletest.dir/all' failed
make[1]: *** [CMakeFiles/googletest.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
make failed
```
I've never used googletest before so I'm not sure how to fix this, can you help me out here?

**Comment by manparvesh** [comment]
@Brand-Temp sure, it seems that during your cloning, googletest was not received. It is added as a submodule to the project, so you need to update the submodules in your fork. To do that, you can take a look at [this stackoverflow answer](https://stackoverflow.com/a/1032653)
